name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [lts/*]
        include:
          - os: macos-latest
            node_version: lts/*
          - os: windows-latest
            node_version: lts/*
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: pnpm i
      - run: pnpm t
      - run: pnpm run typecheck
